// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/supplies": {
    params: {};
  };
  "/supplies/:supplyName": {
    params: {
      "supplyName": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/supplies" | "/supplies/:supplyName";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/supplies.tsx": {
    id: "routes/supplies";
    page: "/supplies";
  };
  "routes/supply.tsx": {
    id: "routes/supply";
    page: "/supplies/:supplyName";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/supplies": typeof import("./app/routes/supplies.tsx");
  "routes/supply": typeof import("./app/routes/supply.tsx");
};