// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/addItem": {
    params: {};
  };
  "/supplies": {
    params: {};
  };
  "/supplies/:supplyName": {
    params: {
      "supplyName": string;
    };
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/settings": {
    params: {};
  };
  "/dashboard/profile": {
    params: {};
  };
  "/forms": {
    params: {};
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/addItem" | "/supplies" | "/supplies/:supplyName" | "/dashboard" | "/dashboard/settings" | "/dashboard/profile" | "/forms" | "/contact";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/addItem.tsx": {
    id: "routes/addItem";
    page: "/addItem";
  };
  "routes/supplies.tsx": {
    id: "routes/supplies";
    page: "/supplies";
  };
  "routes/supply.tsx": {
    id: "routes/supply";
    page: "/supplies/:supplyName";
  };
  "routes/dashboard/DashboardLayout.jsx": {
    id: "routes/dashboard/DashboardLayout";
    page: "/dashboard" | "/dashboard/settings" | "/dashboard/profile";
  };
  "routes/dashboard/DashboardHome.jsx": {
    id: "routes/dashboard/DashboardHome";
    page: "/dashboard";
  };
  "routes/dashboard/DashboardSettings.jsx": {
    id: "routes/dashboard/DashboardSettings";
    page: "/dashboard/settings";
  };
  "routes/dashboard/DashboardProfile.jsx": {
    id: "routes/dashboard/DashboardProfile";
    page: "/dashboard/profile";
  };
  "routes/forms.tsx": {
    id: "routes/forms";
    page: "/forms";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/addItem": typeof import("./app/routes/addItem.tsx");
  "routes/supplies": typeof import("./app/routes/supplies.tsx");
  "routes/supply": typeof import("./app/routes/supply.tsx");
  "routes/dashboard/DashboardLayout": typeof import("./app/routes/dashboard/DashboardLayout.jsx");
  "routes/dashboard/DashboardHome": typeof import("./app/routes/dashboard/DashboardHome.jsx");
  "routes/dashboard/DashboardSettings": typeof import("./app/routes/dashboard/DashboardSettings.jsx");
  "routes/dashboard/DashboardProfile": typeof import("./app/routes/dashboard/DashboardProfile.jsx");
  "routes/forms": typeof import("./app/routes/forms.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
};