// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/supplies": {
    params: {};
  };
  "/supplies/:id": {
    params: {
      "id": string;
    };
  };
  "/supplies/add": {
    params: {};
  };
  "/plants": {
    params: {};
  };
  "/plants/:id": {
    params: {
      "id": string;
    };
  };
  "/plants/add": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/dashboard/settings": {
    params: {};
  };
  "/dashboard/profile": {
    params: {};
  };
  "/forms": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/auth": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/supplies" | "/supplies/:id" | "/supplies/add" | "/plants" | "/plants/:id" | "/plants/add" | "/dashboard" | "/dashboard/settings" | "/dashboard/profile" | "/forms" | "/contact" | "/auth";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/about.tsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/supplies.tsx": {
    id: "routes/supplies";
    page: "/supplies" | "/supplies/:id" | "/supplies/add";
  };
  "routes/supplies/$id.jsx": {
    id: "routes/supplies/$id";
    page: "/supplies/:id";
  };
  "routes/supplies/addItem.tsx": {
    id: "routes/supplies/addItem";
    page: "/supplies/add";
  };
  "routes/plants.tsx": {
    id: "routes/plants";
    page: "/plants" | "/plants/:id" | "/plants/add";
  };
  "routes/plants/$id.jsx": {
    id: "routes/plants/$id";
    page: "/plants/:id";
  };
  "routes/plants/addItem.tsx": {
    id: "routes/plants/addItem";
    page: "/plants/add";
  };
  "routes/dashboard/DashboardLayout.jsx": {
    id: "routes/dashboard/DashboardLayout";
    page: "/dashboard" | "/dashboard/settings" | "/dashboard/profile";
  };
  "routes/dashboard/DashboardHome.jsx": {
    id: "routes/dashboard/DashboardHome";
    page: "/dashboard";
  };
  "routes/dashboard/DashboardSettings.jsx": {
    id: "routes/dashboard/DashboardSettings";
    page: "/dashboard/settings";
  };
  "routes/dashboard/DashboardProfile.jsx": {
    id: "routes/dashboard/DashboardProfile";
    page: "/dashboard/profile";
  };
  "routes/forms.tsx": {
    id: "routes/forms";
    page: "/forms";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/auth.tsx": {
    id: "routes/auth";
    page: "/auth";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/about": typeof import("./app/routes/about.tsx");
  "routes/supplies": typeof import("./app/routes/supplies.tsx");
  "routes/supplies/$id": typeof import("./app/routes/supplies/$id.jsx");
  "routes/supplies/addItem": typeof import("./app/routes/supplies/addItem.tsx");
  "routes/plants": typeof import("./app/routes/plants.tsx");
  "routes/plants/$id": typeof import("./app/routes/plants/$id.jsx");
  "routes/plants/addItem": typeof import("./app/routes/plants/addItem.tsx");
  "routes/dashboard/DashboardLayout": typeof import("./app/routes/dashboard/DashboardLayout.jsx");
  "routes/dashboard/DashboardHome": typeof import("./app/routes/dashboard/DashboardHome.jsx");
  "routes/dashboard/DashboardSettings": typeof import("./app/routes/dashboard/DashboardSettings.jsx");
  "routes/dashboard/DashboardProfile": typeof import("./app/routes/dashboard/DashboardProfile.jsx");
  "routes/forms": typeof import("./app/routes/forms.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/auth": typeof import("./app/routes/auth.tsx");
};