import { useLoaderData, Outlet, Link } from "react-router";
import { FaPlus, FaDownload } from "react-icons/fa";
import SuppliesList from "~/components/SuppliesList";

// Import your type safe route contract generated by React Router v7
import type { Route } from "./+types/supplies";

// Import safely from your server-only file
import { getPresignedDownloadUrl } from "~/data/s3.server";
import { getSupplies } from "~/data/supplies.server";

interface Supply {
  _id: string;
  description: string;
  amount: string;
  units: string;
  imageLocation?: string; // This will hold our temporary presigned URL
  location: string;
  type: string;
  volume: string;
}

interface LoaderData {
  items: Supply[];
}

// Server-side loader: Fetches data from MongoDB AND generates URLs
export async function loader(): Promise<LoaderData> {
  console.log("SUPPLIES LOADER");

  const suppliesData = (await getSupplies()) as
    | { items?: Supply[] }
    | undefined;
  const items = suppliesData?.items ?? [];

  // Map every item in your array to resolve its signed download URL concurrently
  const itemsWithUrls = await Promise.all(
    items.map(async (item) => {
      if (!item.imageLocation) return item;

      try {
        // Swap the internal file path/key with a temporary presigned URL

        const secureUrl = await getPresignedDownloadUrl(item.imageLocation);

        console.log(
          `.   rrrrr.   .  Signed URL for item ${item._id}:`,
          secureUrl,
        );
        return { ...item, imageLocation: secureUrl };
      } catch (error) {
        console.error(`Error signing URL for item ${item._id}:`, error);
        return item; // Fallback to item as-is if signing fails
      }
    }),
  );
  console.log("**** in supplies.server.js, items:", items);
  return { items };
}

export function HydrateFallback() {
  return <p>Loading Supplies...</p>;
}

export default function Supplies() {
  // TypeScript now infers the type safely from the loader return
  const { items } = useLoaderData<typeof loader>();
  // console.log(".   $$$$.  Supplies items:", items);

  return (
    <>
      <Outlet />
      <main>
        <section className="w-full bg-gray-100 p-2 rounded-md mb-2 flex items-center justify-center">
          <div className="w-md flex items-center justify-between">
            <Link
              to="add"
              className="flex bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 px-2 rounded-md transition duration-300 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-opacity-75 items-center gap-2"
            >
              <FaPlus />
              <span>Add Expense</span>
            </Link>
            <a
              className="flex bg-purple-600 hover:bg-purple-700 text-white font-bold py-2 px-2 rounded-md transition duration-300 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-opacity-75 items-center gap-2 mr-2"
              href="/expenses/raw"
            >
              <FaDownload />
              <span>Load Raw Data</span>
            </a>
          </div>
        </section>
        {/* Safely pass the actual array down */}
        <SuppliesList supplies={items} />
      </main>
    </>
  );
}
